[package]
name = "munnel"
version = "0.1.0"
edition = "2018"

[dependencies]
log = "0.4.14"
log4rs = "0.12.0"
uuid = { version = "0.8.2", features = ["serde", "v4"] }
tokio = { version = "1.13.0", features = ["full"] }

